import type { LanguageCode } from "./types";

/**
 * UI-chrome translations. When a parent picks their language, the ENTIRE
 * interface flips — buttons, labels, quiz feedback — not just the letter
 * explanation. The English block defines the required keys; TypeScript
 * guarantees every other language provides all of them.
 */
const en = {
  tagline: "Understand before you sign.",
  steps: ["Letter", "Understand", "Check", "Sign", "Done"],
  folder: "Family folder",

  // Intake
  intakeTitle: "1. What did the school send?",
  schoolName: "School name",
  schoolNamePh: "e.g. Lincoln Middle School",
  pasteLabel: "Paste the letter",
  pastePh: "Paste the full text of the school letter here...",
  wantLang: "I want to understand it in…",
  photoTake: "📷 Take a photo",
  photoPaste: "Paste instead",
  photoTitle: "Take a photo of the letter",
  photoHint: "Opens your camera on mobile, or choose a file",
  photoReading: "Reading your letter…",
  photoRetake: "📷 Retake",
  photoAlt: "Captured letter",
  photoErrSelect: "Please select an image file.",
  photoErrRead: "Could not read the letter.",
  photoErrGeneric: "Something went wrong.",
  explainBtn: "Explain this letter →",
  privacyNote:
    "Your signed receipts and family folder stay in this browser — no account, no database. To explain a letter, its text is sent to an AI service and is not stored by Sabi. Use the demo samples if you prefer nothing leaves your device.",
  stage1: "Reading the letter…",
  stage2: "Preparing your explanation…",
  stage3: "Almost ready…",
  errPaste: "Paste the letter text (or use a sample) first.",
  errGeneric: "Something went wrong. Please try again.",

  // Explanation
  askWhat: "📌 What they ask",
  ifSign: "✅ If you sign",
  ifWait: "⏸️ If you wait",
  keyFacts: "🔎 Key facts in this letter",
  risks: "⚠️ What signing means",
  rights: "🛡️ Your rights",
  readAloud: "🔊 Read aloud",
  stop: "⏹ Stop",
  speaking: "Speaking…",
  toQuiz: "I read it — check my understanding →",
  urgencyAction: "Action required",
  letterTypes: { consent: "Consent", iep: "IEP meeting", discipline: "Discipline", meeting: "Meeting", generic: "Letter" },
  urgencyResponse: "Response needed",
  by: "by",
  aiEngine: "AI engine",
  demoEngine: "Demo engine — add LLM_API_KEY for full AI",

  // Quiz
  quizTitle: "3. Quick check — no grades, just certainty",
  quizSub: "Three short questions. If something is unclear, we explain again.",
  checkAnswers: "Check my answers →",
  answerAll: "Answer all three to continue",
  passed: "✅ You understand this letter.",
  toSign: "Taking you to sign…",
  almost: "Almost — {n} to revisit.",
  tryAgain: "Try again",
  explainAgain: "🔊 Explain to me again",
  simplerLoading: "Preparing a simpler explanation…",
  simplerTitle: "Here it is in simpler words:",

  // Sign
  signTitle: "4. Sign when you are sure",
  signSub:
    "Your signature creates a receipt: what was explained, in your language, and that you confirmed understanding.",
  replyLabel: "Your reply to the school (in English, written for you)",
  draft: "✍️ Draft it",
  drafting: "Writing…",
  replyPh: "Tap 'Draft it' and Sabi writes a polite reply you can send as-is.",
  signBtn: "Sign & create my receipt →",
  signFirst: "Sign above to continue",
  signHint: "Sign above with finger or mouse",
  signatureCaptured: "Signature captured",
  clearBtn: "Clear",

  // Done + folder
  doneTitle: "Done. You understood — then you signed.",
  doneSub: "Your receipt is saved in the family folder.",
  receipt: "🖨️ View / print receipt",
  newLetter: "+ New letter",
  signed: "SIGNED",
  draftStatus: "DRAFT",
};

export type UiStrings = typeof en;

const es: UiStrings = {
  tagline: "Entienda antes de firmar.",
  steps: ["Carta", "Entender", "Revisar", "Firmar", "Listo"],
  folder: "Carpeta familiar",
  intakeTitle: "1. ¿Qué envió la escuela?",
  schoolName: "Nombre de la escuela",
  schoolNamePh: "ej. Escuela Secundaria Lincoln",
  pasteLabel: "Pegue la carta",
  pastePh: "Pegue aquí el texto completo de la carta de la escuela...",
  wantLang: "Quiero entenderla en…",
  photoTake: "📷 Tomar una foto",
  photoPaste: "Pegar el texto",
  photoTitle: "Tome una foto de la carta",
  photoHint: "Abre su cámara en el celular, o elija un archivo",
  photoReading: "Leyendo su carta…",
  photoRetake: "📷 Tomar otra",
  photoAlt: "Carta fotografiada",
  photoErrSelect: "Elija un archivo de imagen.",
  photoErrRead: "No pudimos leer la carta.",
  photoErrGeneric: "Algo salió mal.",
  explainBtn: "Explicar esta carta →",
  privacyNote:
    "Sus recibos firmados y su carpeta familiar se quedan en este navegador — sin cuenta ni base de datos. Para explicar una carta, su texto se envía a un servicio de IA y Sabi no lo guarda. Use las cartas de ejemplo si prefiere que nada salga de su dispositivo.",
  stage1: "Leyendo la carta…",
  stage2: "Preparando su explicación…",
  stage3: "Casi listo…",
  errPaste: "Pegue el texto de la carta (o use un ejemplo) primero.",
  errGeneric: "Algo salió mal. Inténtelo de nuevo.",
  askWhat: "📌 Lo que piden",
  ifSign: "✅ Si firma",
  ifWait: "⏸️ Si espera",
  keyFacts: "🔎 Datos clave de la carta",
  risks: "⚠️ Qué significa firmar",
  rights: "🛡️ Sus derechos",
  readAloud: "🔊 Leer en voz alta",
  stop: "⏹ Detener",
  speaking: "Hablando…",
  toQuiz: "La leí — revisar mi comprensión →",
  urgencyAction: "Acción requerida",
  letterTypes: { consent: "Consentimiento", iep: "Reunión IEP", discipline: "Disciplina", meeting: "Reunión", generic: "Carta" },
  urgencyResponse: "Respuesta requerida",
  by: "antes de",
  aiEngine: "Motor de IA",
  demoEngine: "Motor de demo — agregue LLM_API_KEY para IA completa",
  quizTitle: "3. Repaso rápido — sin notas, solo certeza",
  quizSub: "Tres preguntas cortas. Si algo no está claro, lo explicamos otra vez.",
  checkAnswers: "Revisar mis respuestas →",
  answerAll: "Responda las tres para continuar",
  passed: "✅ Usted entiende esta carta.",
  toSign: "La llevamos a firmar…",
  almost: "Casi — {n} para repasar.",
  tryAgain: "Intentar de nuevo",
  explainAgain: "🔊 Explíquemelo otra vez",
  simplerLoading: "Preparando una explicación más simple…",
  simplerTitle: "Se lo explicamos más simple:",
  signTitle: "4. Firme cuando esté seguro",
  signSub:
    "Su firma crea un recibo: qué se explicó, en su idioma, y que usted confirmó su comprensión.",
  replyLabel: "Su respuesta a la escuela (en inglés, escrita para usted)",
  draft: "✍️ Redactarla",
  drafting: "Escribiendo…",
  replyPh: "Toque «Redactarla» y Sabi escribe una respuesta educada que puede enviar tal cual.",
  signBtn: "Firmar y crear mi recibo →",
  signFirst: "Firme arriba para continuar",
  signHint: "Firme arriba con el dedo o el ratón",
  signatureCaptured: "Firma capturada",
  clearBtn: "Borrar",
  doneTitle: "Listo. Entendió — y luego firmó.",
  doneSub: "Su recibo está guardado en la carpeta familiar.",
  receipt: "🖨️ Ver / imprimir recibo",
  newLetter: "+ Carta nueva",
  signed: "FIRMADA",
  draftStatus: "BORRADOR",
};

const fr: UiStrings = {
  tagline: "Comprendre avant de signer.",
  steps: ["Lettre", "Comprendre", "Vérifier", "Signer", "Terminé"],
  folder: "Dossier familial",
  intakeTitle: "1. Qu'a envoyé l'école ?",
  schoolName: "Nom de l'école",
  schoolNamePh: "ex. Collège Lincoln",
  pasteLabel: "Collez la lettre",
  pastePh: "Collez ici le texte complet de la lettre de l'école...",
  wantLang: "Je veux la comprendre en…",
  photoTake: "📷 Prendre une photo",
  photoPaste: "Coller le texte",
  photoTitle: "Prenez une photo de la lettre",
  photoHint: "Ouvre votre appareil photo sur mobile, ou choisissez un fichier",
  photoReading: "Lecture de votre lettre…",
  photoRetake: "📷 Reprendre",
  photoAlt: "Lettre photographiée",
  photoErrSelect: "Veuillez choisir un fichier image.",
  photoErrRead: "Nous n'avons pas pu lire la lettre.",
  photoErrGeneric: "Une erreur est survenue.",
  explainBtn: "Expliquer cette lettre →",
  privacyNote:
    "Vos reçus signés et votre dossier familial restent dans ce navigateur — sans compte ni base de données. Pour expliquer une lettre, son texte est envoyé à un service d'IA et n'est pas conservé par Sabi. Utilisez les lettres d'exemple pour que rien ne quitte votre appareil.",
  stage1: "Lecture de la lettre…",
  stage2: "Préparation de l'explication…",
  stage3: "Presque prêt…",
  errPaste: "Collez d'abord le texte de la lettre (ou utilisez un exemple).",
  errGeneric: "Une erreur est survenue. Veuillez réessayer.",
  askWhat: "📌 Ce qu'on demande",
  ifSign: "✅ Si vous signez",
  ifWait: "⏸️ Si vous attendez",
  keyFacts: "🔎 Points clés de la lettre",
  risks: "⚠️ Ce que signifie signer",
  rights: "🛡️ Vos droits",
  readAloud: "🔊 Lire à voix haute",
  stop: "⏹ Arrêter",
  speaking: "Lecture…",
  toQuiz: "Je l'ai lue — vérifier ma compréhension →",
  urgencyAction: "Action requise",
  letterTypes: { consent: "Consentement", iep: "Réunion IEP", discipline: "Discipline", meeting: "Réunion", generic: "Lettre" },
  urgencyResponse: "Réponse requise",
  by: "avant le",
  aiEngine: "Moteur IA",
  demoEngine: "Moteur démo — ajoutez LLM_API_KEY pour l'IA complète",
  quizTitle: "3. Vérification rapide — pas de notes, juste la certitude",
  quizSub: "Trois questions courtes. Si quelque chose n'est pas clair, on réexplique.",
  checkAnswers: "Vérifier mes réponses →",
  answerAll: "Répondez aux trois pour continuer",
  passed: "✅ Vous comprenez cette lettre.",
  toSign: "Passons à la signature…",
  almost: "Presque — {n} à revoir.",
  tryAgain: "Réessayer",
  explainAgain: "🔊 Réexpliquez-moi",
  simplerLoading: "Préparation d'une explication plus simple…",
  simplerTitle: "Voici une explication plus simple :",
  signTitle: "4. Signez quand vous êtes sûr",
  signSub:
    "Votre signature crée un reçu : ce qui a été expliqué, dans votre langue, et que vous avez confirmé votre compréhension.",
  replyLabel: "Votre réponse à l'école (en anglais, rédigée pour vous)",
  draft: "✍️ Rédiger",
  drafting: "Rédaction…",
  replyPh: "Touchez « Rédiger » et Sabi écrit une réponse polie à envoyer telle quelle.",
  signBtn: "Signer et créer mon reçu →",
  signFirst: "Signez ci-dessus pour continuer",
  signHint: "Signez ci-dessus avec le doigt ou la souris",
  signatureCaptured: "Signature capturée",
  clearBtn: "Effacer",
  doneTitle: "Terminé. Vous avez compris — puis signé.",
  doneSub: "Votre reçu est enregistré dans le dossier familial.",
  receipt: "🖨️ Voir / imprimer le reçu",
  newLetter: "+ Nouvelle lettre",
  signed: "SIGNÉE",
  draftStatus: "BROUILLON",
};

const pt: UiStrings = {
  tagline: "Entenda antes de assinar.",
  steps: ["Carta", "Entender", "Conferir", "Assinar", "Pronto"],
  folder: "Pasta da família",
  intakeTitle: "1. O que a escola enviou?",
  schoolName: "Nome da escola",
  schoolNamePh: "ex. Escola Municipal Lincoln",
  pasteLabel: "Cole a carta",
  pastePh: "Cole aqui o texto completo da carta da escola...",
  wantLang: "Quero entendê-la em…",
  photoTake: "📷 Tirar uma foto",
  photoPaste: "Colar o texto",
  photoTitle: "Tire uma foto da carta",
  photoHint: "Abre a câmera no celular, ou escolha um arquivo",
  photoReading: "Lendo a sua carta…",
  photoRetake: "📷 Tirar outra",
  photoAlt: "Carta fotografada",
  photoErrSelect: "Escolha um arquivo de imagem.",
  photoErrRead: "Não conseguimos ler a carta.",
  photoErrGeneric: "Algo deu errado.",
  explainBtn: "Explicar esta carta →",
  privacyNote:
    "Seus recibos assinados e sua pasta familiar ficam neste navegador — sem conta e sem banco de dados. Para explicar uma carta, o texto é enviado a um serviço de IA e não é guardado pelo Sabi. Use as cartas de exemplo se preferir que nada saia do seu dispositivo.",
  stage1: "Lendo a carta…",
  stage2: "Preparando sua explicação…",
  stage3: "Quase pronto…",
  errPaste: "Cole o texto da carta (ou use um exemplo) primeiro.",
  errGeneric: "Algo deu errado. Tente novamente.",
  askWhat: "📌 O que pedem",
  ifSign: "✅ Se você assinar",
  ifWait: "⏸️ Se você esperar",
  keyFacts: "🔎 Fatos importantes da carta",
  risks: "⚠️ O que assinar significa",
  rights: "🛡️ Seus direitos",
  readAloud: "🔊 Ler em voz alta",
  stop: "⏹ Parar",
  speaking: "Falando…",
  toQuiz: "Li a carta — conferir meu entendimento →",
  urgencyAction: "Ação necessária",
  letterTypes: { consent: "Consentimento", iep: "Reunião IEP", discipline: "Disciplina", meeting: "Reunião", generic: "Carta" },
  urgencyResponse: "Resposta necessária",
  by: "antes de",
  aiEngine: "Motor de IA",
  demoEngine: "Motor demo — adicione LLM_API_KEY para IA completa",
  quizTitle: "3. Conferência rápida — sem notas, só certeza",
  quizSub: "Três perguntas curtas. Se algo não ficar claro, explicamos de novo.",
  checkAnswers: "Conferir minhas respostas →",
  answerAll: "Responda as três para continuar",
  passed: "✅ Você entende esta carta.",
  toSign: "Indo para a assinatura…",
  almost: "Quase — {n} para revisar.",
  tryAgain: "Tentar de novo",
  explainAgain: "🔊 Explique de novo",
  simplerLoading: "Preparando uma explicação mais simples…",
  simplerTitle: "Aqui está de forma mais simples:",
  signTitle: "4. Assine quando tiver certeza",
  signSub:
    "Sua assinatura cria um recibo: o que foi explicado, no seu idioma, e que você confirmou o entendimento.",
  replyLabel: "Sua resposta à escola (em inglês, escrita para você)",
  draft: "✍️ Escrever",
  drafting: "Escrevendo…",
  replyPh: "Toque em «Escrever» e o Sabi escreve uma resposta educada pronta para enviar.",
  signBtn: "Assinar e criar meu recibo →",
  signFirst: "Assine acima para continuar",
  signHint: "Assine acima com o dedo ou o mouse",
  signatureCaptured: "Assinatura capturada",
  clearBtn: "Limpar",
  doneTitle: "Pronto. Você entendeu — e depois assinou.",
  doneSub: "Seu recibo está salvo na pasta da família.",
  receipt: "🖨️ Ver / imprimir recibo",
  newLetter: "+ Nova carta",
  signed: "ASSINADA",
  draftStatus: "RASCUNHO",
};

const ar: UiStrings = {
  tagline: "افهم قبل أن توقّع.",
  steps: ["الرسالة", "الفهم", "التحقق", "التوقيع", "تم"],
  folder: "ملف العائلة",
  intakeTitle: "1. ماذا أرسلت المدرسة؟",
  schoolName: "اسم المدرسة",
  schoolNamePh: "مثال: مدرسة لينكولن",
  pasteLabel: "الصق الرسالة",
  pastePh: "الصق نص رسالة المدرسة كاملاً هنا...",
  wantLang: "أريد أن أفهمها بـ…",
  photoTake: "📷 التقط صورة",
  photoPaste: "الصق النص",
  photoTitle: "التقط صورة للرسالة",
  photoHint: "يفتح الكاميرا على الهاتف، أو اختر ملفاً",
  photoReading: "نقرأ رسالتك…",
  photoRetake: "📷 التقط مرة أخرى",
  photoAlt: "صورة الرسالة",
  photoErrSelect: "اختر ملف صورة.",
  photoErrRead: "لم نتمكن من قراءة الرسالة.",
  photoErrGeneric: "حدث خطأ ما.",
  explainBtn: "اشرح هذه الرسالة →",
  privacyNote:
    "تُ حفظ إيصالاتك الموقعة ومجلد عائلتك في هذا المتصفح — بلا حساب ولا قاعدة بيانات. لشرح رسالة، يُرسَل نصها إلى خدمة ذكاء اصطناعي ولا يقوم سابي بتخزينه. استخدم الرسائل النموذجية إذا أردت ألا يخرج أي شيء من جهازك.",
  stage1: "نقرأ الرسالة…",
  stage2: "نجهّز شرحك…",
  stage3: "على وشك الانتهاء…",
  errPaste: "الصق نص الرسالة (أو استخدم نموذجاً) أولاً.",
  errGeneric: "حدث خطأ ما. حاول مرة أخرى.",
  askWhat: "📌 ما الذي يطلبونه",
  ifSign: "✅ إذا وقّعت",
  ifWait: "⏸️ إذا انتظرت",
  keyFacts: "🔎 حقائق مهمة في الرسالة",
  risks: "⚠️ ماذا يعني التوقيع",
  rights: "🛡️ حقوقك",
  readAloud: "🔊 اقرأ بصوت عالٍ",
  stop: "⏹ إيقاف",
  speaking: "جارٍ التحدث…",
  toQuiz: "قرأتها — تحقق من فهمي →",
  urgencyAction: "مطلوب إجراء",
  letterTypes: { consent: "موافقة", iep: "اجتماع IEP", discipline: "تأديب", meeting: "اجتماع", generic: "رسالة" },
  urgencyResponse: "مطلوب رد",
  by: "قبل",
  aiEngine: "محرك ذكاء اصطناعي",
  demoEngine: "محرك تجريبي — أضف LLM_API_KEY للذكاء الاصطناعي الكامل",
  quizTitle: "3. فحص سريع — بدون درجات، فقط تأكد",
  quizSub: "ثلاثة أسئلة قصيرة. إذا كان شيء غير واضح، نشرحه مرة أخرى.",
  checkAnswers: "تحقق من إجاباتي →",
  answerAll: "أجب على الأسئلة الثلاثة للمتابعة",
  passed: "✅ أنت تفهم هذه الرسالة.",
  toSign: "ننقلك للتوقيع…",
  almost: "على وشك — {n} لإعادة النظر.",
  tryAgain: "حاول مجدداً",
  explainAgain: "🔊 اشرح لي مرة أخرى",
  simplerLoading: "نجهّز شرحاً أبسط…",
  simplerTitle: "إليك الشرح بأبسط طريقة:",
  signTitle: "4. وقّع عندما تكون متأكداً",
  signSub: "توقيعك ينشئ إيصالاً: ما تم شرحه، بلغتك، وأنك أكدت الفهم.",
  replyLabel: "ردك على المدرسة (بالإنجليزية، مكتوب لك)",
  draft: "✍️ اكتبه",
  drafting: "جارٍ الكتابة…",
  replyPh: "اضغط «اكتبه» ويكتب سابي رداً مهذباً يمكنك إرساله كما هو.",
  signBtn: "وقّع وأنشئ إيصالي →",
  signFirst: "وقّع بالأعلى للمتابعة",
  signHint: "وقّع بالأعلى بإصبعك أو بالفأرة",
  signatureCaptured: "تم حفظ التوقيع",
  clearBtn: "مسح",
  doneTitle: "تم. فهمت — ثم وقّعت.",
  doneSub: "إيصالك محفوظ في ملف العائلة.",
  receipt: "🖨️ عرض / طباعة الإيصال",
  newLetter: "+ رسالة جديدة",
  signed: "موقّعة",
  draftStatus: "مسودة",
};

export const UI: Record<LanguageCode, UiStrings> = { en, es, fr, pt, ar };
